### ISSUE TITLE
Change text to lowercase

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-volunteer#1]
Lowercase and make sure its aligned with the right box on `wfp-jpo-country`
![fff](https://cloud.githubusercontent.com/assets/19909772/18552601/5e6fa09e-7b5d-11e6-9e61-8f82f7c3760f.PNG)

Lowercase
![hhhh](https://cloud.githubusercontent.com/assets/19909772/18552658/ac8c2496-7b5d-11e6-943f-209f64f76b8b.PNG)

**Comment by jrah** [comment]
I will make these changes.

FYI: These are uppercase in the comp and the text script provided.

**Comment by danielapizzurro** [comment]
@jrah I know but for these minor changes we decided not to re-do the mockups. So you would still find some uppercase texts on mockups, and text to be changed. If you see them, you can switch to lowercase; in doubt, please ask.

**Comment by danielapizzurro** [comment]
sorry @jrah I did not explain myself well. By "aligned with the right box on `wfp-jpo-country`" I meant that the text would have the same style as the label **Looking for more information** on that page (so, bold and 1.25rem). 

And "Who can volunteer for WFP" could be 2.25rem as for the other 3-pieces section on the career page.
