### ISSUE TITLE
browsers and media queries issues 

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-volunteer#4]
- [x] Chrome 53/IE 11/Opera 39/Safari 9.2  + Windows 7: at 1024x768 menu doesn't show compact

![menu](https://cloud.githubusercontent.com/assets/19909772/18592838/06fb048e-7c39-11e6-8cdf-e3f869df5cff.PNG)

- [ ] Chrome 53/IE11/Firefox 48 + Windows 7: at sm and smaller media queries, form fields are not aligned
![form fields](https://cloud.githubusercontent.com/assets/19909772/18592995/c18e4810-7c39-11e6-8b17-c3657a7d83c1.PNG)

**Comment by matthewmorek** [comment]
@jrah Make sure to use responsive padding classes for the form, as it looks like the padding is applied to look good on desktop viewports.
