### ISSUE TITLE
3 pieces section: insufficient contrast

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-volunteer#5]
HTML Code sniffer reports 3 errors on this section for insufficient contrast.
At the moment is not a major issue, but I just wanted to report it to remember for later.
![insuff contrast](https://cloud.githubusercontent.com/assets/19909772/18593565/4468187c-7c3c-11e6-8105-b18eb7a7f7d0.PNG)

**Comment by jrah** [comment]
<img width="999" alt="screenshot 2016-09-19 12 51 05" src="https://cloud.githubusercontent.com/assets/1245961/18631049/c48f8d3c-7e67-11e6-964f-ac80f46458f6.png">

This is `bg-blue-7` which passes WCAG2AA but perhaps it is _too_ dark.

**Comment by matthewmorek** [comment]
@jrah You can use `$bg-blue-brand`, which uses the WFP Blue with a AA-compliant hue. Ref: https://github.com/wfp/ui/blob/master/scss/css/_theme.scss#L34

**Comment by jrah** [comment]
Thanks @matthewmorek 

@danielapizzurro I will leave you to close this issue if you are happy with it. 
<img width="1007" alt="screenshot 2016-09-19 13 18 27" src="https://cloud.githubusercontent.com/assets/1245961/18631725/92629904-7e6b-11e6-9377-bab2d6ffb3d8.png">
